# =============================================
# Build config
# =============================================

# src config
src:              src

# dest config
root:             out
dest:             <%= site.root %>
dist:             dist
assets:           <%= site.dest %>/

# Metadata
date:             <%= new Date() %>
data:             data/*.{json,yml}

# Templates
templates:        <%= site.src %>
partials:         <%= site.src %>/_partials
layouts:          <%= site.src %>/_layouts
layoutext:        .hbs
layout:           default

# Extensions
helpers:          <%= site.src %>/helpers/*.js
plugins:
  - assemble-contrib-contextual

# Theme
styles:           styles
components:       <%= site.styles %>/components


# =============================================
# Project metadata
# =============================================

# GitHub
username:         assemble
name:             assemble # change to <%= pkg.name %>
download:
  source:         <%= pkg.homepage %>/archive/master.zip


# =============================================
# Site metadata
# =============================================

company:          <%= pkg.author %>
title:            PresenTense Magazine Archives
brand:            <%= site.title %>
lead:

version:          <%= pkg.version %>
description:      <%= pkg.description %>

# Links
url:
  repo:           <%= pkg.homepage %>
  bugs:           <%= pkg.bugs.url %>?state=open
  ghpages:        https://<%= site.username %>.github.io/<%= pkg.name %>/

  # Site
  domain:         http://assemble.io/
  about:          <%= site.url.domain %>/about/
  blog:           <%= site.url.domain %>/blog/


# SEO/SEM
ga:
  id:             UA-XXXXXX-XX
  domain:         assemble.github.io
  siteid:         false

  # Google Tags (see: https://www.google.com/tagmanager/)
  tags:           GTM-KHGHNC

# Comments
disqus:
  enabled:        true
  shortname:      <%= pkg.name %>

# Social
social:
  twitter:
    via:          assemblejs
    username:     assemblejs
    related:      jonschlinkert:Assemble core team.
  facebook:       false
  linkedin:       false
  gplus:          false
  hn:             false
  google:         false

# Sharing
sharing:
  twitter:        false
  facebook:       false
  gplus:          false
  hn:             false
  google:         false